// tp5/my-react-auth-app/src/components/LoginForm/Dashboard/Dashboard.jsx
import React from "react";
import "./Dashboard.css";
import { useNavigate } from "react-router-dom";

const Dashboard = () => {
  const navigate = useNavigate();

  const handleLogout = () => {
    localStorage.removeItem("isAuthenticated");
    navigate("/");
  };

  return (
    <div className="dashboard-layout">
      <aside className="sidebar">
        <img
            src="/images/enset_logo.png"
            alt="ENSET Logo"
            className="logo"
        />
        <nav className="nav-links">
          <a href="#"> Dashboard</a>
          <a href="#"> Products</a>
          <a href="#"> Upload File</a>
          <button className="logout-btn" onClick={handleLogout}>
             Logout
          </button>
        </nav>
      </aside>
      <main className="main-content">
      </main>
    </div>
  );
};

export default Dashboard;

// tp5/angular-auth-app/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  constructor(private auth: AuthService) {}

  logout() {
    this.auth.logout();
  }
}

<div class="dashboard">
    <aside class="sidebar">
      <img src="/images/enset_logo.png" alt="logo" />
      <nav>
        <a href="#"> Dashboard</a>
        <a href="#"> Products</a>
        <a href="#"> Upload File</a>
        <button (click)="logout()"> Logout</button>
      </nav>
    </aside>
    <main class="content">
      <h2>Welcome to your dashboard</h2>
    </main>
  </div>
